services:
  dashboard:
    image: sensor-dashboard/sensor-dashboard-app:latest
    depends_on:
      - dashboard-api
    ports:
      - "8080:80"
    networks:
      - dashboard-network
  dashboard-api:
    image: sensor-dashboard/sensor-dashboard-api:latest
    depends_on:
      - sidabi
    ports:
      - "5000:5000"
    networks:
      - dashboard-network
    volumes:
      - dashboard-volume:/var/files:ro
    environment:
      - DATABASE_URL=postgresql+psycopg2://lucas:qR4e6Y10FkNeOnU6JAit@sidabi-instance-1.csraqxx4fdwz.us-east-1.rds.amazonaws.com/sidabi
      - SECRET_KEY=58AFD8134FB1788329CE68B8AFE85
      - FILE_LOCATION=/var/files/
  sidabi:
    image: sensor-dashboard/sidabi:latest
    ports:
      - "8082:8082"
    networks:
      - dashboard-network
    volumes:
      - dashboard-volume:/var/www/html/sidabi/biodata/files/sessao_arquivos
networks:
  dashboard-network:
    driver: bridge
volumes:
  dashboard-volume:
